### PR TITLE
Add ORCiD ID in AbstractRetrieval

### LINKED ISSUE #217: Add ORCiD ID in AbstractRetrieval
A query by PID for a publication returns an author list. However, that author list does not contain ORCID.
```python
from pybliometrics.scopus import abstract_retrieval
ab = abstract_retrieval.AbstractRetrieval('10.1016/j.physleta.2020.126262', view='FULL')
ab.authors
[Author(auid=57192676604, indexed_name='Kolmes E.J.', surname='Kolmes', given_name='E. J.', affiliation='60003269'),
 Author(auid=56809243300, indexed_name='Ochs I.E.', surname='Ochs', given_name='I. E.', affiliation='60003269'),
 Author(auid=57210964512, indexed_name='Mlodik M.E.', surname='Mlodik', given_name='M. E.', affiliation='60003269'),
 Author(auid=55944266200, indexed_name='Fisch N.J.', surname='Fisch', given_name='N. J.', affiliation='60003269')]
```

### PR DESCRIPTION
**Pull request by astrochun**
Closes #217

- [x] Updated `AbstractRetrieval.authorgroup` property
- [x] Updated unit test, docs

### CODE REVIEW

**Comment by Michael-E-Rose** [comment]
I think the class' docstring is missing, isn't?

**Comment by astrochun** [comment]
> I think the class' docstring is missing, isn't?

Yes, it seems so.

**Comment by Michael-E-Rose** [comment]
What I meant is to update the docstring for `AbstractRetrieval().authorgroup`: https://github.com/pybliometrics-dev/pybliometrics/blob/master/pybliometrics/scopus/abstract_retrieval.py#L51-L58

**Comment by astrochun** [comment]
> What I meant is to update the docstring for `AbstractRetrieval().authorgroup`: https://github.com/pybliometrics-dev/pybliometrics/blob/master/pybliometrics/scopus/abstract_retrieval.py#L51-L58

Ah, you said class docstrings and that confused me. Thanks for clarifying. That should do it and I found a minor typo

**Comment by astrochun** [comment]
Unless I'm mistaken, there has not been a new PyPI release with this or #216. Is that correct?

**Comment by Michael-E-Rose** [comment]
I bumped 3.2.0 two days ago, see https://pybliometrics.readthedocs.io/en/stable/classes/AbstractRetrieval.html#pybliometrics.scopus.AbstractRetrieval.authorgroup

I guess you didn't see it because I didn't link you on twitter this time ;)

**Comment by astrochun** [comment]
> I bumped 3.2.0 two days ago, see https://pybliometrics.readthedocs.io/en/stable/classes/AbstractRetrieval.html#pybliometrics.scopus.AbstractRetrieval.authorgroup
> 
> I guess you didn't see it because I didn't link you on twitter this time ;)

HAHA. It helps.

**Pull request merged**
